version: '3.8'

services:
  app:
    build: .
    ports:
      - "8081:80"
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_PORT=3306
      - DB_DATABASE=Bookstore
      - DB_USERNAME=root
      - DB_PASSWORD=123
    volumes:
      - /var/www/html/vendor
      - .:/var/www/html

  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: 123
      MYSQL_DATABASE: Bookstore
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  db_data:
