name: Test Create Tag

on:
  workflow_dispatch:

jobs:
  create_tag:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Git
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"

      - name: Create and push tag
        run: |
          TAG="test-v1.0.$(date +%s)"
          git tag $TAG
          git push origin $TAG
