name: Test Release Upload
on:
  push

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Create dummy zip
        run: |
          mkdir artifact
          echo "Hello release test" > artifact/hello.txt
          zip -r artifact.zip artifact

      - name: Ensure Release Exists
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # Ako release/tag ne postoji, kreira ga
          if ! gh release view "4.4.2" &>/dev/null; then
            gh release create "4.4.2" -t "Test Release 4.4.2" -n "Release za testiranje GitHub CLI"
          fi

      - name: Upload asset with gh CLI
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: gh release upload "4.4.2" artifact.zip --clobber
